arXiv/arxiv-search

- Dockerfile-elasticsearch
- README.md
- docker-compose.yml
- mappings/DocumentMapping.json
- populate_test_metadata.py
- search/domain.py
- search/process/transform.py
- search/services/index.py
- tests/data/1709.01849v1.indexable.json
- tests/test_transform.py
The analysis settings in this PR represent a fairly simple (but hopefully not totally unreasonable) first stab; I fully expect the analysis settings to change as we make further progress and learn more through test searches. A new dockerfile for ES + installed plugin as well as a docker-compose file for the ES+Kibana stack are provided to facilitate testing.
> First stab at application of document analysis settings

- tests/examples/advanced_search.feature.example
- tests/examples/author_search.feature.example
- tests/examples/ordering_pagination.feature.example
- tests/examples/simple_search.feature.example
Okay....let me know whether this is even in the ballpark of what we are looking for.
I realize that some of this might be able to be condensed into a scenario outline or data table, but I wasn't sure how the structure might change depending on how we can check for output on the tests.
Thoughts, suggestions, additions, edits appreciated.
> add first draft behavioral test examples

- DECISIONS.md
- search/templates/search/advanced_search.html
- search/templates/search/author_search.html
This is one way that we could commemorate decisions. I prefer to have this information tracked and versioned right along with the code.
> added a decision log

- lintstats.sh
- search/agent/consumer.py
- search/controllers/advanced/__init__.py
- search/controllers/authors/__init__.py
- search/controllers/simple/__init__.py
- search/domain/author.py
- search/domain/base.py
- search/process/transform.py
- search/services/metadata.py
An initial round of type checking. Doesn't yet capture completely missing annotations, but gets to the default settings of `mypy --ignore-missing-imports`. Will open a new issue to deal with those, but wanted to merge early and often!
> Initial typechecking task/ARXIVNG-285

- search/services/index.py
- search/templates/search/advanced_search.html
- search/templates/search/author_search.html
- search/templates/search/search-macros.html
- search/templates/search/search.html
> ARXIVNG-297 disallow pagination beyond ES limit

- search/templates/search/advanced_search.html
- search/templates/search/author_search.html
- search/templates/search/search-macros.html
- search/templates/search/search.html
Help text is a rough pass, edits/suggestions welcome.
Can't get full accessibility check without touching base, but did what I could for search templates.
> ARXIVNG-294 accessibility, ARXIVNG-310 ARXIVNG-303 help text

- search/routes/ui.py
This change is based on recommendations from the Arachni security scanner.
> Address UI redress (clickjacking) vulnerability

- requirements/dev.txt
- requirements/prod.txt
- search/templates/search/search-macros.html
Depends somewhat on https://github.com/cul-it/arxiv-base/pull/41
Please also note proposed change to requirements/dev.txt, which facilitates testing of arxiv-base changes (though in an earlier, uncommitted version I was pointing to this feature branch in that repo rather than develop).
> Add "mathjax" class to title in search results template

- search/controllers/advanced/forms.py
- search/services/index/__init__.py
- tests/test_controller_advanced.py
> ARXIVNG-383 - Support for "All fields" in advanced search

- search/controllers/advanced/forms.py
- search/controllers/simple/forms.py
Author ID -> arXiv author ID
Identifier -> arXiv identifier
Journal ref -> Journal reference (this one for consistent labeling)
> Update drop-down labels

- search/controllers/advanced/__init__.py
- search/controllers/advanced/tests.py
- search/controllers/simple/__init__.py
- search/controllers/simple/tests.py
> ARXIVNG-416 return a 400 Bad Request if the pagination parameters are funky

- search/process/transform.py
- search/services/index/authors.py
- search/services/index/prepare.py
This should privilege results in which more than one author responds to the query.
> ARXIVNG-549 changed score mode to sum hits on nested documents (authors)

- search/controllers/simple/__init__.py
- search/services/index/authors.py
- search/services/index/prepare.py
- search/services/index/util.py
- wsgi.py
This should promote results that match on multiple fields, e.g. an author name and a title term.
> ARXIVNG-557 include boosted multi-match for title, abstract, authors when searching by all fields

- search/controllers/advanced/__init__.py
- search/controllers/advanced/forms.py
- search/routes/ui.py
- tests/test_advanced_search.py
This implements the shortcut functionality in the classic system.
> ARXIVNG-548 shortcut routes for archives in advanced search

- search/services/index/authors.py
- search/services/index/simple.py
This was working for "all" fields, but not for specific searches on author ID or ORCID. This fixes the problem.
>  ARXIVNG-805 fixed poorly-constructed query for author ID and ORCID ID

- search/controllers/advanced/__init__.py
- search/controllers/advanced/forms.py
- search/controllers/advanced/tests.py
- search/domain/base.py
- search/routes/ui.py
- search/services/index/advanced.py
- search/templates/search/advanced_search.html
Defaults to original submission date, per ticket.
> ARXIVNG-1002 added feature to apply date filters to submitted or announced date

- search/services/index/highlighting.py
See https://github.com/mozilla/bleach/issues/381 for background on the bug. This was leading to some search results causing a 500 error, due to an unhandled exception raised by Bleach when we are stripping user-generated HTML from the abstract.
What I've done here is fall back to simply HTML-escaping the abstract when Bleach fails. The worst that can happen is some user-entered HTML shows up unrendered in the abstract.
I also took the liberty of replacing double dollar signs to single, which should decrease the number of unrenderable equations.
> ARXIVNG-889 workaround for bug in bleach that causes errors on some equations

- search/services/index/prepare.py
This is a patch version to address bug ARXIVNG-1089
> Pre-release merge for v0.4.1

- .gitignore
- docs/source/conf.py
- update-docs.sh
Updated documentation at https://arxiv.github.io/arxiv-search/
Added update-docs script to help with future updates, per metadocs.
> ARXIVNG-1114: Adding update-docs.sh script, update intersphinx refs

- search/routes/api/__init__.py
- search/routes/api/exceptions.py
- search/routes/ui.py
There were a variety of mypy errors being thrown on Travis CI.
For some reason running `pipenv run mypy -p search` did NOT reveal the same errors, but the linter in VSCode did reveal them. Very curious - perhaps an older typeshed in some shadow environment? VSCode is pipenv-aware though, so rather confused.
At any rate, this should see a successful build, and if so, then we should be able to merge #235
> mypy ignores for a variety of errors

- search/static/js/fieldset.js
- search/templates/search/advanced_search.html
- search/templates/search/search-macros.html
Minor edits. Adds a new message box with instructions for how to do a subcategory search, some  layout adjustments to balance the left and right columns, and bring more clarity to the search terms box. 
Attached are screenshots of the new and the existing layouts.
New:
Existing:
> adds subcategory description, minor layout adjustments

- README.md
> Update documentation URL in README.md

- recent_docs_updated.sql
This sql find papers with metadata/author updates during the previous hour. Here are test files:
nexus:/users/e-prints/arxiv-search/recent_docs_updated.*
> Arxivng 3692 kubeshift search indexing

- .travis.yml
- Dockerfile-api
- Dockerfile-classic-api
- lintstats.sh
- search/services/index/__init__.py
- search/services/index/results.py
This is ready for prod on the cit web vms.
> ARXIVNG-3918-es.search() to use post

- .github/ISSUE_TEMPLATE/python-app.yml
- .github/workflows/python-app.yml
- search/factory.py
combining auto testing branch with branch that fixes the tests so tests can actually pass
> Adding autotesting to GitHub workflows
