arXiv/arxiv-search

search/controllers/advanced/forms.py
search/controllers/authors/forms.py
search/controllers/simple/__init__.py
search/controllers/simple/forms.py
search/controllers/util.py
search/services/index.py
search/templates/search/advanced_search.html
search/templates/search/search.html
tests/test_controller_advanced.py
tests/test_controller_authors.py
tests/test_controller_simple.py
tests/test_services_index.py

Wildcards should now be working in simple, author, and advanced search. 
Basically what I did was...
- Introduce a function in ``search.services.index`` called ``_wildcardEscape`` that escapes any wildcards in string literals, and then checks to see if there are any remaining wildcard characters that should be treated as such.
- Introduce a wrapper for elasticsearch_dsl.Q that returns a "wildcard" query part if the querystring has a wildcard in it, and otherwise falls back to whatever query type was specified.
Made a couple of other minor opportunistic improvements.

ARXIVNG-262 added support for wildcards and literals

---

populate_test_metadata.py
requirements.txt
search/agent/__init__.py
search/agent/base.py
search/agent/consumer.py
search/controllers/simple/forms.py
search/domain/base.py
search/process/transform.py
search/services/index.py
search/services/metadata.py
tests/test_agent.py

I refactored ``populate_test_metadata`` to use ``search.agent.consumer.MetadataRecordProcessor``, which now has everything except the Kinesis glue. This should be sufficient to populate the test index for beta deploy, once we've stabilized the search document.

ARXIVNG-279 Implemented indexing agent for populating test index

---

mappings/DocumentMapping.json
search/controllers/authors/__init__.py
search/controllers/authors/forms.py
search/domain/author.py
search/process/transform.py
search/services/index.py
search/static/js/fieldset.js
search/templates/search/author_search.html

There is now a dijunct full-name field on the search form....
The ``full_name`` field has this mapping:
```json
"full_name": {
"type": "text",
"analyzer": "folding"
},
```
with a new analyzer:
```
"folding": {
"type": "custom",
"tokenizer": "standard",
"filter": [
"icu_folding",
"lowercase"
]
},
```
Also changes the way that they query is displayed in the search results:

ARXIVNG-308 user may optionally search by author full name (text match, not keyword)

---

README.md
search/controllers/advanced/forms.py
search/controllers/authors/forms.py
search/controllers/simple/forms.py
search/controllers/util.py
tests/test_controller_advanced.py
tests/test_controller_authors.py
tests/test_controller_simple.py

Adds whitespace stripping to:
- Simple form
- ``query``
- Author form
- ``surname``
- ``forename``
- ``fullname``
- Advanced form
- ``term``
Fixes #77

ARXIVNG-322 padding whitespace is stripped from query

---

search/templates/search/advanced_search.html

I ended up smashing two unrelated issues together in this branch because they were both tiny...probably not best practice but seemed a bit more efficient.
ARXIVNG-377 addresses a confusion from beta testing that some users didn't understand the "+" button without a label.
ARXIVNG-368 help text changes - I left the original example, wasn't sure if it is completely superseded by the new examples. Also made formatting changes for consistency.
There is also an untracked label correction caught by accessibility checker - duplicate labels on the date radio buttons were caused by the label tag that is removed in this PR.

ARXIVNG-377 ARXIVNG-368 form label adjustments and help text adjustments

---

search/templates/search/advanced_search.html
search/templates/search/search.html

Screenshot taken doing testing on metadata.total+1000, since my test dataset doesn't have > 1,000 records.
Plus opportunistic adjustments to help text (added author bits that will be included with ARXIVNG-372, and applied help tips from advanced to simple search for parity).

Add comma separator to thousands place in title

---

lintstats.sh
search/controllers/advanced/forms.py
search/controllers/advanced/tests.py
search/controllers/simple/forms.py
search/domain/base.py
search/routes/ui.py
search/services/index/__init__.py
search/services/index/results.py
search/templates/search/advanced_search.html
search/templates/search/search-macros.html
search/templates/search/search.html

ARXIVNG-379
- After performing a simple search, when the user clicks on the "advanced search" link their query is used to auto-populate the advanced search form.
- When the user selects a page size and/or sort order, that selection is preserved across searches and search routes.
ARXIVNG-380
- Increased all page size options by 100%
- Set default page size to 50
ARXIVNG-382
- Added ``MultiFormatDateField`` to support variable-precision dates.
- Updated placeholder text in date range fields to ``YYYY[-MM[-DD]]``.

ARXIVNG-379 Order, page size, query propagate between pages

---

.coveragerc
search/controllers/__init__.py
search/controllers/simple/__init__.py
search/controllers/tests.py
search/domain/base.py
search/routes/ui.py
search/services/index/__init__.py
search/services/index/prepare.py
search/services/index/results.py
search/services/index/tests/tests.py
search/templates/search/search.html

This is pretty bare-bones. If we need to return more information, we can do that. The requirements for Kubernetes liveness are [pretty simple](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request), and this PR meets those.

ARXIVNG-401 health check endpoint

---

.travis.yml
README.md
search/agent/__init__.py
search/agent/base.py
search/agent/tests/test_base_consumer.py
search/agent/tests/tests.py
search/services/index/prepare.py
tests/integration/test_search_integration.py

https://github.com/cul-it/arxiv-search/issues/151 was occurring because we (at some point) switched to ``simple_query_string`` queries for title and abstract, and ``simple_query_string`` does not support the ``?`` wildcard operator (only ``*``). Switching to ``query_string`` fixes this.
Given https://github.com/cul-it/arxiv-search/issues/143 (which is reasonable), I switched the ``default_operator`` to ``AND``. 
Note that using the ``query_string`` does open up some additional functionality for users (e.g. using parens to group terms, boolean operators, etc).  Since this only applies to title and abstract, I'm not sure whether we want to actually document this, or let them discover it on their own. I'm leaning toward the latter.
Note that this was branched from ``task/ARXIVNG-419``, so it …

ARXIVNG-418 fixed wildcard search, changed default querystring behavior

---

search/controllers/advanced/forms.py
search/controllers/simple/__init__.py
search/controllers/simple/forms.py
search/services/index/__init__.py
search/services/index/authors.py
search/services/index/prepare.py
wsgi.py

To provide better support for special characters, we should consider a different tokenizer for non-keyword fields. Until then, this will at least allow the search to proceed, even if the special characters don't make it past the analyzer.

ARXIVNG-552 escaping special characters correctly, removed string coercion from wsgi wrapper

---

search/services/index/authors.py
search/services/index/prepare.py
search/services/index/results.py

This also provides a short-term fix for ARXIVNG-543, which is due to erroneous stripping of punctuation characters from author names. The least we can do is process the query in the same way that we prepared the search document. This is *not* a long-term fix.
@eawoods Eager to hear if this improves some of the cases that you were looking at.

ARXIVNG-549 suppress stopwords in author search

---

tests/examples/authors_combined_terms.example

Simple writeup of terms and expected results used in current manual testing for author searches.
Tests drawn from actual feedback cases submitted during search 0.1 release.

add test cases for combined terms

---

mappings/DocumentMapping.json
search/controllers/advanced/__init__.py
search/controllers/advanced/forms.py
search/controllers/advanced/tests.py
search/controllers/simple/__init__.py
search/controllers/simple/tests.py
search/controllers/tests.py
search/controllers/util.py
search/domain/advanced.py
search/domain/base.py
search/process/tests.py
search/process/transform.py
search/routes/ui.py
search/services/index/__init__.py
search/services/index/advanced.py
search/services/index/authors.py
search/services/index/highlighting.py
search/services/index/prepare.py
search/services/index/results.py
search/services/index/simple.py
search/services/index/tests/test_results.py
search/services/index/tests/tests.py
search/services/index/util.py
search/templates/search/advanced_search.html
search/templates/search/search-macros.html
search/templates/search/search.html
tests/test_advanced_search.py

Things were getting way too complex, which made search difficult to debug and to reason about. This is an attempt to make things much simpler.
One big change is that "all fields" is not just a disjunction of queries for each field. This introduces a ``combined`` field in the index that is used as the primary search document. A query against ``combined`` is conjoined with a modified disjunct (need only partial match on a field) across queries for each field (must also match at least one field-based search), so that we get hit highlighting. There are a few small things to wrap up on the "modified" part.
I also removed non-utf8 fields from the search document. Now title and abstract are populated from their utf8 counterparts in DocMeta (need to clean up a couple of tests about that).
This …

ARXIVNG-544 ARXIVNG-549 ARXIVNG-552 refactored query-building for simplicity, clarity

---

README.md
audit.py
search/agent/consumer.py
search/services/index/__init__.py

Added the script ``audit.py`` in the root of the project, implemented with click. This takes a list of paper IDs (including version affix), and outputs a list of missing paper IDs. A full scan may take one to three hours, depending on your internet connection. 
From the docstring:
```
Check the index for missing papers.
Uses HEAD requests to the document endpoint using each paper ID in the
provided list. Uses multiprocessing with a configurable number of worker
processes to speed things up.
Parameters
----------
id_list : str
Should be a path to a file with paper IDs. There should be one paper ID
per line. Paper IDs should include version affixes.
batch_size : int
Number of records per batch. Each batch is divided into equal chunks
and distributed across workers. Smaller batches mean more …
```

ARXIVNG-556 Audit tool for missing records

---

mappings/DocumentMapping.json
search/process/tests.py
search/process/transform.py
search/services/index/authors.py

Unfortunately this will require a reindex from docmeta, as it changes the structure of the data (``authors.initials`` goes from being a list to being a str). I can't say that I'm 100.0% happy with this. It's difficult to get precision on forename parts (e.g. initials occur in order) and recall (e.g. with wildcards). In this version, if the forename part of a structured query contains a wildcard, we do a query_string query on the forename. Otherwise, we do a match_phrase_prefix, which preserves term order.

ARXIVNG-741 order of initials is respected in author name queries

---

search/services/index/authors.py
search/services/index/prepare.py
search/services/index/util.py

We weren't offering a wildcard query on those fields. This checks for wildcards, and if present returns a wildcard query instead of a match.

ARXIVNG-775 handling wildcards in msc and acm classification fields

---

.gitignore
Dockerfile-elasticsearch
Dockerfile-kibana
bulk_index.py
search/process/tests.py
search/services/index/authors.py

This turned out to be a pretty simple bug. The document path "authors" was hard-coded in a place where it aught to been set by a function parameter (i.e. variously using "authors" or "owners").

ARXIVNG-1001 fixed bug that prevented author-owner matches when individuating name parts

---

search/controllers/util.py

Many of the queries that we run involve subqueries that treat whitespace delimited terms separately, including `query_string` queries. We were checking for wildcard characters at the beginning of the query string, but not at the beginning of individual terms. This PR fixes that.

ARXIVNG-977 catch queries with terms that start with a wildcard

---

search/controllers/advanced/__init__.py
search/controllers/advanced/forms.py
search/controllers/simple/__init__.py
search/controllers/simple/forms.py
search/domain/base.py
search/routes/ui.py
search/templates/search/advanced_search.html
search/templates/search/search-macros.html
search/templates/search/search.html

Users can indicate whether to show or hide abstracts in search results. The last selection made by the user is stored in the preferences cookie. I would have preferred a checkbox, but since browsers don't send False values for checkboxes, we end up in an indeterminate situation when we're using the cookie. Hence the radio field.
Here's the simple search form:
Here's the advanced search form:

ARXIVNG-978 implemented feature to hide abstracts in search results

---

search/controllers/advanced/forms.py
search/controllers/simple/forms.py
search/controllers/tests.py
search/controllers/util.py
search/services/index/authors.py
search/services/index/prepare.py
search/services/index/tests/test_util.py
search/services/index/tests/tests.py
search/services/index/util.py

The arXiv ID partial ("papernum") detection is stricter than in the classic search but unlike classic search, if a papernum is detected the query is not limited to the paper ID field. In other words, if a user enters what looks like a papernum in the "all fields" search, that term will actually get queried across all fields.

ARXIVNG-983 Support searches for seven-digit arXiv ID partials

---

search/templates/search/advanced_search.html
search/templates/search/base.html

I tightened up the layout a little to reduce unnecessary vertical white space. We had a display block for the "Simple Search" link that needed a bit of adjustment as a result.
Also, added some width limiters so that very long queries don't push the "Simple Search" link off the page.

ARXIVNG-982 Make "back" link on advanced search results more obvious

---

Dockerfile-agent
search/config.py
search/templates/search/base.html

Per ARXIVNG-1009 I also updated the link to the release notes, and updated the version number displayed with that link.

ARXIVNG-1008 incremented version number in feedback collector to 0.4

---

Pipfile
Pipfile.lock
docs/source/search_api.rst
schema/resources/Document.json
schema/search.yaml
search/config.py
search/controllers/api/__init__.py
search/domain/api.py
search/domain/base.py
search/routes/api/__init__.py
search/routes/api/serialize.py
search/routes/api/tests/test_api.py
search/services/index/__init__.py
search/services/index/prepare.py
search/services/index/results.py

Response content (both from ES to the app, and app to the client) can get really big, because our source documents are huge and our metadata documents are huge. 
This adds support for limiting fields to only a subset of those in the source document. In the index service, we look for ``.include_fields`` on the domain query object, and use those to do [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html). We can use this in the future to improve performance for the search UI.
In the ``search.routes.api`` module, we look also look at the query object to decide what to send back to the client. The ``.serializer`` submodule only grabs fields from the result document if they are explicitly listed. The client should use the …

ARXIVNG-1206 ARXIVNG-1212 Include only a subset of fields in query response, filter by license

---

schema/search.yaml
search/domain/base.py

Fairly self-explanatory. Adding size and start to OpanAPI parameters list.
Also adjusts the `Query.MAXIMUM_size` to 2000 to match old export.arxiv.org settings.

Adding size and start to OpenAPI parameters list ARXIVNG-1895 ARXIVNG-1896

---

schema/resources/AtomXML.yaml
schema/search-xml.yaml

This PR that includes the OpenAPI Schema for the current incarnation of the arXiv API, which is documented at: https://arxiv.org/help/api
It primarily focuses on two files:
- `schema/search-xml.yaml` contains the API schema
- `schema/resources/AtomXML.yaml` contains the schema for the Atom+XML response, whcih was defined with the [Representing XML docs](https://swagger.io/docs/specification/data-models/representing-xml/)
I haven't yet done validation on these files (or any of the schema files, for that matter), but want to check out the [Swagger Viewer VS Code Extension](https://marketplace.visualstudio.com/items?itemName=Arjun.swagger-viewer)
We can determine whether validation of schemas is in-scope for this PR or whether we want a sprint on that across all repos.

Atom+XML OpenAPI Schema ARXIVNG-1518

---

Pipfile
Pipfile.lock

This will switch search to arxiv-base v0.5.15 which has a template that points to our new matomo instance.

update base to 0.5.15 to support new analytics [HOTFIX]

---

Pipfile
Pipfile.lock

This upgrades the arxiv-base dependency to 0.15.8.post1, which adds a new category and new category aliases to the taxonomy.

Pre-release merge for search v0.5.5

---

search/controllers/__init__.py
search/controllers/advanced/__init__.py
search/controllers/advanced/tests.py
search/controllers/api/__init__.py
search/controllers/simple/__init__.py
search/controllers/simple/tests.py
search/controllers/tests.py
search/routes/api/tests/test_api.py
search/routes/ui.py
search/services/fulltext.py
search/services/metadata.py
tests/test_exceptions.py

As the `arxiv.status` module is deprecated I removed all references in the `arixiv.search` to that module.

Remove all references to deprecated arxiv.status module.

---

Dockerfile-index

Fix pipenv call in Dockerfile.index.

---

bulk_index.py

This adds --quiet and --no-cache to bulk_index.py
See https://arxiv-org.atlassian.net/browse/ARXIVNG-3760

Quiet bulk indexing without cache

---

search/static/css/search.css
search/templates/search/advanced_search.html

Two small changes to fix the display of the boolean operator in the advanced search.
A new css rule hides it only for the first row. And an inline css rule in the form is removed because it was hiding it on all rows.

fixes display of boolean operator in advanced search form

---

README.md
search/controllers/advanced/__init__.py
search/controllers/advanced/tests.py
search/controllers/simple/__init__.py
search/controllers/simple/tests.py
search/services/index/__init__.py
search/services/index/exceptions.py
search/templates/search/base.html
search/tests/test_searches.py
tests/test_exceptions.py

The status code for when ElasticSearch cannot parse or run a query was a 500. It is now a 400.
This is to distinguish between cases where the client is sending queries that cannot be run from cases where the app is having an unexpected internal error. Having this is intended to assist in our current effort reduce 500 errors in the system.
ARXIVNG-5111

Change HTTP response code for queries that cannot run from 500 to 400 

---

search/templates/search/base.html

Very small commit to remove the jira feedback collector link from base.html in search.
It seems likely to be an oversight that the link is still there after all the other collector links were removed.  The reason for removal of those links was the low number of actionable tickets coming in (plus a lot of spam) vs. the high burden of parsing tickets and responding to users. That seems to be holding true for the search collector form also. We mostly get feedback around author name searches not working right, and they are quite correct, but it is a known issue that we cannot take action on at this time.
On a related note, we are working towards a plan for continuous, higher quality, qualitative feedback. Feedback is important, but we want it to be actionable on some level, and not leave …

Removes jira feedback collector link from search

---

search/templates/search/base.html

There have been several users reporting that the "feedback?" button on the advanced search page is non-functional. This PR removes that button.

removes non-functional Feedback? button
